name: 'ACR: Docker Push'

on:
  workflow_call:


jobs:
  az-acr-push:
    name: "Azure: ACR Build & Push"
    runs-on: ubuntu-latest
    environment: dev
    env:
      DOCKERFILE: ${{ vars.DOCKERFILE || 'Dockerfile' }}
      AZURE_CONTAINER_REGISTRY: ${{ secrets.AZURE_CONTAINER_REGISTRY }}
      ACR_LOGIN_USERNAME: ${{ secrets.ACR_LOGIN_USERNAME }}
      ACR_LOGIN_PASSWORD: ${{ secrets.ACR_LOGIN_PASSWORD }}
    strategy:
      matrix:
        platform: [amd64, arm64]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3      
      - name: Log into registry
        uses: docker/login-action@v3
        with:
          registry: "${{ env.AZURE_CONTAINER_REGISTRY }}"
          username: "${{ env.ACR_LOGIN_USERNAME }}"
          password: "${{ env.ACR_LOGIN_PASSWORD }}"
      
      - name: Build & Push
        uses: docker/build-push-action@v5
        with:
          cache-from: type=gha
          cache-to: type=gha,mode=max
          file: ${{ env.DOCKERFILE }}
          tags: ${{ env.AZURE_CONTAINER_REGISTRY }}/${{ github.event.repository.name }}:${{ matrix.platform}}
          push: true
          build-args: |
            platform=linux/${{ matrix.platform}}

      - name: Build & Push - Replace branch
        if: ${{ github.ref != github.repository.default_branch }}
        uses: docker/build-push-action@v5
        with:
          cache-from: type=gha
          cache-to: type=gha,mode=max
          file: ${{ env.DOCKERFILE }}
          tags: ${{ env.AZURE_CONTAINER_REGISTRY }}/${{ github.event.repository.name }}:${{ matrix.platform}}-${{ github.ref_name }}
          push: true
          build-args: |
            platform=linux/${{ matrix.platform}}