name: 'ACR: Docker Push Test'

on:
  workflow_call:

jobs:
  az-acr-push:
    name: "Docker: Build & Push (Test)"
    runs-on: ubuntu-latest
    environment: dev
    env:
      AZURE_CONTAINER_REGISTRY: ${{ vars.AZURE_CONTAINER_REGISTRY }}
      ACR_LOGIN_USERNAME: ${{ secrets.ACR_LOGIN_USERNAME }}
      ACR_LOGIN_PASSWORD: ${{ secrets.ACR_LOGIN_PASSWORD }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Configure branch name
        id: branch_name
        run: echo "GH_REF_NAME=${${{ github.ref_name }}//\//-}" >> $GITHUB_OUTPUT
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3      
      - name: Log into registry
        uses: docker/login-action@v3
        with:
          registry: "${{ env.AZURE_CONTAINER_REGISTRY }}"
          username: "${{ env.ACR_LOGIN_USERNAME }}"
          password: "${{ env.ACR_LOGIN_PASSWORD }}"
      
      - name: Build & Push ${{ github.event.repository.name }}:test-${{ steps.branch_name.outputs.GH_REF_NAME }}
        uses: docker/build-push-action@v5
        with:
          cache-from: type=gha
          cache-to: type=gha,mode=max
          file: 'dev.Dockerfile'
          tags: ${{ env.AZURE_CONTAINER_REGISTRY }}/${{ github.event.repository.name }}:test-${{ steps.branch_name.outputs.GH_REF_NAME }}
          push: true
          build-args: |
            platform=linux/amd64
            label=dockerfile-path=https://github.com/${{ github.repository }}/blob/${{ github.sha }}/dev.Dockerfile