name: 'ACR Docker Push'

on:
  workflow_call:

env:
  IMAGE_TAG_STATIC: latest

jobs:
  az-acr-push:
    name: "Azure: Docker Container Build & Push"
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Log into registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.ACR_NAME }}.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}
      
      - name: Build & Push - Static Image Tag
        uses: docker/build-push-action@v2
        with:
          push: true
          file: ${{ vars.DOCKERFILE || 'Dockerfile' }}
          tags: ${{ secrets.ACR_NAME }}.azurecr.io/${{ github.event.repository.name }}:${{ env.IMAGE_TAG_STATIC }}
          build-args: |
            platform=linux/amd64
