name: 'ACR: Docker Push'

on:
  workflow_call:

jobs:
  az-acr-push:
    name: "Docker: Build & Push"
    runs-on: ${{ matrix.platform == 'amd64' && 'ubuntu-latest' || 'macos-14'}}
    environment: dev
    env:
      AZURE_CONTAINER_REGISTRY: ${{ vars.AZURE_CONTAINER_REGISTRY }}
      ACR_LOGIN_USERNAME: ${{ secrets.ACR_LOGIN_USERNAME }}
      ACR_LOGIN_PASSWORD: ${{ secrets.ACR_LOGIN_PASSWORD }}
      DEV_CONTAINER_REGISTRY: ${{ vars.DEV_CONTAINER_REGISTRY }}
      DEV_LOGIN_USERNAME: ${{ secrets.DEV_LOGIN_USERNAME }}
      DEV_LOGIN_PASSWORD: ${{ secrets.DEV_LOGIN_PASSWORD }}
    strategy:
      matrix:
        platform: [amd64, arm64]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: 'true'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/${{ matrix.platform }}

      - name: Log into Azure registry
        uses: docker/login-action@v3
        with:
          registry: "${{ env.AZURE_CONTAINER_REGISTRY }}"
          username: "${{ env.ACR_LOGIN_USERNAME }}"
          password: "${{ env.ACR_LOGIN_PASSWORD }}"

      - name: Log into DEV registry
        if: ${{ github.repository == 'code-kern-ai/gates-runtime' }}
        uses: docker/login-action@v3
        with:
          registry: "${{ env.DEV_CONTAINER_REGISTRY }}"
          username: "${{ env.DEV_LOGIN_USERNAME }}"
          password: "${{ env.DEV_LOGIN_PASSWORD }}"

      - name: Configure branch name
        id: branch_name
        run: echo "GH_REF_NAME=$(echo ${{ github.ref_name }} | sed 's|/|-|g')" >> $GITHUB_OUTPUT

      - name: Build & Push ${{ github.event.repository.name }}:${{ matrix.platform }}-${{ steps.branch_name.outputs.GH_REF_NAME }}
        if: ${{ github.ref_name != github.repository.default_branch }}
        uses: docker/build-push-action@v5
        with:
          push: true
          file: 'Dockerfile'
          tags: ${{ env.AZURE_CONTAINER_REGISTRY }}/${{ github.event.repository.name }}:${{ matrix.platform }}-${{ steps.branch_name.outputs.GH_REF_NAME }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            platform=linux/${{ matrix.platform }}
            label=dockerfile-path=https://github.com/${{ github.repository }}/blob/${{ github.sha }}/Dockerfile

      - name: Build & Push ${{ github.event.repository.name }}:${{ matrix.platform }}-gpu
        if: ${{ hashFiles('gpu.Dockerfile') != '' }}
        uses: docker/build-push-action@v5
        with:
          push: true
          file: 'gpu.Dockerfile'
          tags: ${{ env.AZURE_CONTAINER_REGISTRY }}/${{ github.event.repository.name }}:${{ matrix.platform }}-gpu
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            platform=linux/${{ matrix.platform }}
            label=dockerfile-path=https://github.com/${{ github.repository }}/blob/${{ github.sha }}/gpu.Dockerfile