name: "GitHub: Delete Branch"

on:
  workflow_call:

jobs:
  az-acr-delete:
    name: 'Azure: Delete Branch Images'
    runs-on: ubuntu-latest
    environment: dev
    env:
      AZURE_CONTAINER_REGISTRY: ${{ vars.AZURE_CONTAINER_REGISTRY }}
      ACR_LOGIN_USERNAME: ${{ secrets.ACR_LOGIN_USERNAME }}
      ACR_LOGIN_PASSWORD: ${{ secrets.ACR_LOGIN_PASSWORD }}
    strategy:
      matrix:
        platform: [amd64, arm64]
    steps:
      - name: Azure Cloud Login
        uses: Azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      
      - name: Delete Branch Container Image
        uses: azure/cli@v2
        with:
          inlineScript: |
            az acr repository delete \
              --name ${{ env.AZURE_CONTAINER_REGISTRY }} \
              --image ${{ github.event.repository.name }}:${{ matrix.platform}}-${{ github.ref_name }} \
              --yes
  
  gh-delete-branch:
    name: 'GitHub: Delete Branch'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.TOKEN_GITHUB }}
      
      - name: Delete Branch
        shell: bash
        run: git push origin --delete ${{ github.ref }}