name: 'K8: Destroy'

on:
  workflow_call:

# Special permissions required for OIDC authentication
permissions:
  id-token: write
  contents: read
  actions: read

jobs:
  k8-cluster-destroy:
    name: 'K8: Destroy Cluster Namespace'
    runs-on: ubuntu-latest
    environment: ${{ github.ref_name }}
    env:
      KUBERNETES_NAMESPACE: "${{ vars.KUBERNETES_NAMESPACE }}"
      KUBERNETES_CLUSTER_NAME: "${{ vars.KUBERNETES_CLUSTER_NAME }}"
      KUBERNETES_MANIFEST_PATH: "${{ vars.KUBERNETES_MANIFEST_PATH }}"
      AZURE_RESOURCE_GROUP: "${{ vars.AZURE_RESOURCE_GROUP }}"
      AZURE_STORAGE_ACCOUNT: ${{ vars.AZURE_STORAGE_ACCOUNT }}
      AZURE_STORAGE_FILE_SHARE: ${{ vars.AZURE_STORAGE_FILE_SHARE }}
      AZCOPY_VERSION: "v10"
    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v4

    - name: GitHub Configuration
      run: git config --global url."https://oauth2:${{ secrets.TOKEN_GITHUB }}@github.com".insteadOf https://github.com

    - name: Clone cicd-deployment-scripts
      run: git clone https://github.com/code-kern-ai/cicd-deployment-scripts.git

    - name: Install AzCopy
      run: bash cicd-deployment-scripts/az/install_azcopy.sh -v ${{ env.AZCOPY_VERSION }}
    
    # Install the latest version of Kubernetes CLI and configure the Kubernetes CLI configuration file with a Kubernetes Cloud user API token
    - name: Azure Login
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  
    - name: Azure CLI
      uses: azure/cli@v2
      env:
        AZCOPY_AUTO_LOGIN_TYPE: AZCLI
      with:
        inlineScript: |
          azcopy remove \
            "https://${{ env.AZURE_STORAGE_ACCOUNT }}.file.core.windows.net/${{ env.AZURE_STORAGE_FILE_SHARE }}" \
            --exclude-path='
                caddy/Caddyfile;
                kratos/identity.schema.json;
                kratos/kratos.yml;
                oathkeeper/oathkeeeper.yml;
                oathkeeper/access-rules.yml;
                oathkeeper/jwks.json' \
            --recursive=true
  
    # Use kubelogin to configure your kubeconfig for Azure auth
    - name: Set up kubelogin for non-interactive login
      uses: azure/use-kubelogin@v1
      with:
        kubelogin-version: 'v0.0.25'

    - uses: azure/aks-set-context@v3
      with:
        resource-group: ${{ env.AZURE_RESOURCE_GROUP }}
        cluster-name: ${{ env.KUBERNETES_CLUSTER_NAME }}
        admin: 'false'
        use-kubelogin: 'true'

    - name: Destroy Cluster Namespace
      shell: bash
      run: |
        bash cicd-deployment-scripts/k8-cluster/destroy.sh \
          -n ${{ env.KUBERNETES_NAMESPACE }} \
          -s ${{ env.AZURE_STORAGE_ACCOUNT }} \
          -f ${{ env.AZURE_STORAGE_FILE_SHARE }}
    