name: 'K8: Database Upgrade'

on:
  workflow_call:
    inputs:
      alembic_upgrade_rev:
        description: 'Rev of migration to migrate to'
        required: false
        default: 'head'
        type: string
      docker_image_tag:
        description: 'Docker Image Tag'
        required: false
        default: 'latest'
        type: string
    outputs:
      alembic_current_rev:
        description: 'Current Alembic Rev'
        value: ${{ jobs.k8-db-upgrade.outputs.ALEMBIC_CURRENT_REV }}
      alembic_upgraded_rev:
        description: 'Upgraded Alembic Rev'
        value: ${{ jobs.k8-db-upgrade.outputs.ALEMBIC_UPGRADED_REV }}

# Special permissions required for OIDC authentication
permissions:
  id-token: write
  contents: read
  actions: read

jobs:
  k8-db-upgrade:
    name: 'K8: Database Upgrade'
    runs-on: [self-hosted, "${{ github.event_name == 'pull_request' && github.event.pull_request.base.ref || github.ref_name }}"]
    environment: ${{ github.event_name == 'pull_request' && github.event.pull_request.base.ref || github.ref_name }}
    env:
      ENVIRONMENT_NAME: ${{ github.event_name == 'pull_request' && github.event.pull_request.base.ref || github.ref_name }}
      KUBELOGIN_VERSION: "v0.0.25"
      KUBERNETES_CLUSTER_REPO_NAME: "${{ vars.KUBERNETES_CLUSTER_REPO_NAME }}"
      KUBERNETES_CLUSTER_NAME: "${{ vars.KUBERNETES_CLUSTER_NAME }}"
      KUBERNETES_NAMESPACE: "${{ vars.KUBERNETES_NAMESPACE }}"
      KUBERNETES_MANIFEST_PATH: "${{ vars.KUBERNETES_MANIFEST_PATH }}"
      AZURE_RESOURCE_GROUP: "${{ vars.AZURE_RESOURCE_GROUP }}"
      AZURE_CONTAINER_REGISTRY: "${{ vars.AZURE_CONTAINER_REGISTRY }}"
    outputs:
      ALEMBIC_CURRENT_REV: ${{ steps.alembic_command.outputs.ALEMBIC_CURRENT_REV }}
      ALEMBIC_UPGRADED_REV: ${{ steps.alembic_command.outputs.ALEMBIC_UPGRADED_REV }}
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: GitHub Configuration
      run: git config --global url."https://oauth2:${{ secrets.GH_TOKEN }}@github.com".insteadOf https://github.com

    - name: Clone cicd-deployment-scripts
      run: git clone https://github.com/code-kern-ai/cicd-deployment-scripts.git
    
    - name: Clone ${{ env.KUBERNETES_CLUSTER_REPO_NAME }}
      run: git clone https://github.com/code-kern-ai/${{ env.KUBERNETES_CLUSTER_REPO_NAME }}.git

    - name: Azure Cloud Login
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Set up kubelogin for non-interactive login
      uses: azure/use-kubelogin@v1
      with:
        kubelogin-version: ${{ env.KUBELOGIN_VERSION }}

    - uses: azure/aks-set-context@v3
      with:
        resource-group: ${{ env.AZURE_RESOURCE_GROUP }}
        cluster-name: ${{ env.KUBERNETES_CLUSTER_NAME }}
        admin: 'false'
        use-kubelogin: 'true'

    - name: Apply Alembic Migrate
      shell: bash
      id: alembic_command
      run: |
        echo $(cat cicd-deployment-scripts/k8s/db_upgrade.sh)
        bash cicd-deployment-scripts/k8s/db_upgrade.sh \
          -e ${{ env.ENVIRONMENT_NAME }} \
          -d ${{ github.event.repository.name }} \
          -p ${{ github.workspace }}/${{ env.KUBERNETES_CLUSTER_REPO_NAME }} \
          -n ${{ env.KUBERNETES_NAMESPACE }} \
          -r ${{ env.AZURE_CONTAINER_REGISTRY }} \
          -t ${{ inputs.docker_image_tag }} \
          -a ${{ inputs.alembic_upgrade_rev }}